### ISSUE TITLE
response is NaN !!!

### ISSUE THREAD

**Issue by MohammedAliBinTaleb** [paul-shuvo/nodejs-currency-converter#14]
```
    let currencyConverter = new CC({ from: "USD", to: "SAR", amount: 500 });
    let result = await currencyConverter.convert();  ==> result is NaN !!

```

**Comment by paul-shuvo** [comment]
It's working on my side. Could you share some more code and your node version?

**Comment by MohammedAliBinTaleb** [comment]
node.js version = 16.13.0 I am using Next.js as stack of my app but I don't know why it show me NaN

**Comment by paul-shuvo** [comment]
It works on `16.13.0`. You can check it [here](https://runkit.com/6184927360d151000896e73c/619198f3c09e7e0008597c03). I think it might be a Next.js specific issue and the information you have provided is not enough to reproduce the values.

**Comment by paul-shuvo** [comment]
I'm closing this issue as the problem probably is not related to this repo.
