### ISSUE TITLE
Error: Cannot find module 'got'

### ISSUE THREAD

**Issue by siktiruelsatanizm** [paul-shuvo/nodejs-currency-converter#15]
after downloading the module i got this error: Error: Cannot find module 'got'

**Comment by paul-shuvo** [comment]
What's your `node` version and how are you installing the package i.e. `npm`, `yarn`, or from Github?

**Comment by bangbaew** [comment]
> What's your `node` version and how are you installing the package i.e. `npm`, `yarn`, or from Github?

I also get the same error, my node version is 17.2.0, installed with Yarn 3.1.1

**Comment by paul-shuvo** [comment]
The error should be fixed in the latest version ([1.1.7](https://www.npmjs.com/package/currency-converter-lt/v/1.1.7))
