### ISSUE TITLE
Latest version of 'got' is making the currency converter package unstable

### ISSUE THREAD

**Issue by olarotseyi** [paul-shuvo/nodejs-currency-converter#16]
Is it possible for you to set specific versions for got and cheerio rather than "latest"? The latest version of got, which was updated 5 days ago, has "type": "module" in its package.json file thereby making it impossible to import the currency converter using the commonjs require('currency-converter-lt') statement. 'got' Version 11.8.2 worked well before the 'got' upgrade to v12.0.0

**Comment by paul-shuvo** [comment]
You are right. I've already changed the 'got' version and going through tests; will update the package by tonight.

**Comment by olarotseyi** [comment]
Thanks
