### ISSUE TITLE
Result is bigger than input by 100? 

### ISSUE THREAD

**Issue by davidrot** [paul-shuvo/nodejs-currency-converter#17]
I dont care about the rounding, but i guess there is a division by 100 missing.

Using: 
"name": "currency-converter-lt",
"version": "1.1.9",

```
console.log(await currencyConverter.from("USD").to("GBP").amount(100).convert());
// 7400
// 73,54 Pound sterling (google)
console.log(await currencyConverter.from("USD").to("EUR").amount(100).convert());
// 8800 
// 88,15 Euro (google)
console.log(await currencyConverter.from("EUR").to("USD").amount(0.88).convert());
// 99.44
// 1,00 United States Dollar (google)
```

**Comment by paul-shuvo** [comment]
Hi @davidrot, thanks for posting this issue. I will fix the precision issue asap. The other issue you mentioned "_there is a division by 100 missing_", could you elaborate on that; I ran the code [here](https://runkit.com/paul-shuvo/61b945a33cae9200080d294e) and it looks fine. I get the following output when I ran your code:

```
73
88
1.0031999999999999
```

Also, you might be getting a decimal comma (decimal `.` represented in `,` depending on your locale) in your google search results. Let me know if that's the case; if not I'll take a look into that issue as well.

**Comment by paul-shuvo** [comment]
I have addressed the rounding issue. The conversion seems fine and as I haven't heard anything from you, I'm closing this issue.
