### ISSUE TITLE
Big amounts

### ISSUE THREAD

**Issue by ServerDeveloper9447** [paul-shuvo/nodejs-currency-converter#19]
The converter provides faulty results on over 4 figure amounts

**Comment by paul-shuvo** [comment]
Could you share your code and the result you're getting?

**Comment by ServerDeveloper9447** [comment]
One example:
![image](https://user-images.githubusercontent.com/86161882/150638096-2215bd2e-a30f-4fc6-9778-439eca845eb1.png)

On google it shows:
![image](https://user-images.githubusercontent.com/86161882/150638121-6ae6c9cf-a314-472e-9f35-0f37f1a1948a.png)

**Comment by paul-shuvo** [comment]
Thanks for posting this issue. It's fixed in the latest release. Let me know if you still find any other issues!
