### ISSUE TITLE
Convertion isn't correct

### ISSUE THREAD

**Issue by giannisker** [paul-shuvo/nodejs-currency-converter#20]
I tried converting 1 JPY to EUR and it returns 76 which is incorrect. The correct number is 0,0076, but I also tried converting 1 CHF to EUR which is 0.95 but its output is 95. The code I used is copy paste from the documentation.

**Comment by paul-shuvo** [comment]
Are you using the latest version? I ran the conversion [here](https://runkit.com/6184927360d151000896e73c/619198f3c09e7e0008597c03) and it looks fine. Could you share your code anyway?

**Comment by clarkjoshualopez** [comment]
I encounter same issue

**Comment by giannisker** [comment]
I ran `yarn list --pattern currency-converter-lt` to see the version of the package and it is the same written in the runkit (1.2.3).  I copy pasted your code to my machine and it returned 95.

**Comment by paul-shuvo** [comment]
I think I figured out the problem; it's the decimal comma(,). Depending on your locale, google result returns either 1,000.00 or 1.000,00 i.e switches the comma and the dot. I'll take a look as soon as I can.

**Comment by paul-shuvo** [comment]
@GiannhsKer @clarkjoshualopez let me know if you still have trouble with the conversion.

**Comment by giannisker** [comment]
No I still have the same issue, I'm connecting from Greece if that helps.

**Comment by paul-shuvo** [comment]
Pass the `isDecimalComma:true` in the constructor as the following: 

```javascript
let currencyConverter = new CC({from:"USD", to:"JPY", amount:100, isDecimalComma:true})
```

**Comment by giannisker** [comment]
That solved it!

**Comment by s-a-n-n-i** [comment]
I get NaN in result.

**Comment by Alekseenkoone** [comment]
i get NaN too.
