### ISSUE TITLE
Webpack Bundling

### ISSUE THREAD

**Issue by fjbatresv** [paul-shuvo/nodejs-currency-converter#22]
First. Really awesome job. Thanks.

I'm trying to use this one in a webpack project. 

But for some reason when it is build I receive a message saying “this is not a valid package for webpack”.

Would be really nice if you can solve this issue.

**Comment by paul-shuvo** [comment]
Hey @fjbatresv , I'll look into the problem asap. Could you share some more information about the error?

**Comment by paul-shuvo** [comment]
I'm closing this issue for now.
