### ISSUE TITLE
When Calling rate() it returns 1

### ISSUE THREAD

**Issue by C-Guards** [paul-shuvo/nodejs-currency-converter#27]
I tried the library recently after I read the documentation, it says that rates() should return rates.

but when I call it returns the number (1) and I tried to figure it out but couldn't detect the issue.

system Info:
NodeJS: 16.14.2
OS: Windows 10

Am I am receiving the right response?

**Comment by paul-shuvo** [comment]
Could you share your code and what currencies are you trying to convert?

**Comment by C-Guards** [comment]
I will close this issue because I thought that rates() function doesn't need to supply an object.
