### ISSUE TITLE
Module parse failed: Unexpected token (5:15)

### ISSUE THREAD

**Issue by sepiisagun** [paul-shuvo/nodejs-currency-converter#29]
I know this issue is already listed on the closed issues. But the latest one was closed without a fix. So here is my version.

The error would be.
```
./node_modules/currency-converter-lt/index.js
Module parse failed: Unexpected token (5:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class CurrencyConverter {
>     currencies = {
|         "AFN": "Afghan Afghani",
|         "ALL": "Albanian Lek",
```

I have this running on react v17.0.2. I tried running it on strapi v3.6.5 and it works there totally fine. Node version I'm using is v14.8.1, npm would be v8.5.5

**Comment by paul-shuvo** [comment]
@sepiisagun it's hard to say what's actually happening without seeing the config and the full error/log. Could you check this [link](https://stackoverflow.com/questions/33469929/you-may-need-an-appropriate-loader-to-handle-this-file-type-with-webpack-and-b) and see if anything helps and let me know?

**Comment by sepiisagun** [comment]
@paul-shuvo uhmm, it somehow worked? I don't know how. But what I did is just rebuild the project and it worked perfectly fine. lol proceeding to close the issue.
