### ISSUE TITLE
RON is not a valid currency

### ISSUE THREAD

**Issue by JuanFAustinSoftware** [paul-shuvo/nodejs-currency-converter#31]
There is an extra space in the string causing RON to not be recognized.
<img width="562" alt="image" src="https://user-images.githubusercontent.com/94373591/171429258-b4977ce1-37ed-49b2-988c-1cfb26d0c454.png">

**Comment by paul-shuvo** [comment]
This issue should be fixed in the latest version ([1.3.1](https://www.npmjs.com/package/currency-converter-lt/v/1.3.1))
