### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by atoyansk** [paul-shuvo/nodejs-currency-converter#35]
Does support typescript in NodeJS? If so, how to import?

**Comment by paul-shuvo** [comment]
You may want to look into [this](https://github.com/paul-shuvo/nodejs-currency-converter/pull/7) pull request.

**Comment by atoyansk** [comment]
Thanks! in order to import, this is the right way? `import * as CC from 'currency-converter-lt';`

**Comment by paul-shuvo** [comment]
@atoyansk That should be the right way, however, I'm yet to test that pull request; so let me know if you come across any issues.

**Comment by atoyansk** [comment]
I'm testing with a Firebase function, like this:

    `import * as CC from 'currency-converter-lt';

    export const createTransfer = async (amount: number) => {
        let converted = new CC({from: 'ILS', to: 'USD', amount: amount, isDecimalComma: true});
        converted.convert().then((response) => {
            return response;
        });
    };`

But because it is a Firebase function, the error is not clear (it just indicates that the response is not returning anything):

Error: Uncaught (in promise): Error: INTERNAL
Error: INTERNAL at new HttpsErrorImpl

**Comment by paul-shuvo** [comment]
@atoyansk I'll look into it and try to add typescript support, but it may take some time.

**Comment by apetrichkovich** [comment]
Hello.
Is there any news about typescript support?

**Comment by apetrichkovich** [comment]
I've updated tsconfig.json to
`{
  "compilerOptions": {
    "allowJs": true,`
and imported class `import * as CurrencyConverter from 'currency-converter-lt';`

That's all folks :)

**Comment by walkingbrad** [comment]
@apetrichkovich My setup still doesn't like the import with those changes, saying the usual in that it wants a type definition file or for me to try and install `@types/currency-convert-lt`.

Here's my `tsconfig.json`. Do you have other settings I don't?
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "dist",
    "rootDir": "src",
    "sourceMap": true,
    "strict": true,
    "target": "ESNext",
    "plugins": [
      {
        "transform": "typia/lib/transform"
      }
    ]
  },
  "include": [
    "src"
  ]
}
```

**Comment by macworldville** [comment]
Can you add the option to configure CORS, API being blocked due to cross-origin
