### ISSUE TITLE
Getting syntax error

### ISSUE THREAD

**Issue by ptatap29** [paul-shuvo/nodejs-currency-converter#38]
After I installed this package. try to import using command 
const CC = require('currency-converter-lt')
am getting Syntax Error : Unexpected =

**Comment by ptatap29** [comment]
node_modules\currency-converter-lt\index.js:6
    "currencies" = {
                 ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

**Comment by paul-shuvo** [comment]
I don't see any quotation ("currencies") marks at line 6. Could specify the version of nodejs and the package you're using.

**Comment by ptatap29** [comment]
that is not quotation on downloading package in index.js file of package we have the class CurrencyConvertor in which there is a object currencies = {......}
That is the place I am getting error

**Comment by ptatap29** [comment]
in the below file:
https://github.com/paul-shuvo/nodejs-currency-converter/blob/master/index.js
line no 5

**Comment by ptatap29** [comment]
Node version I am using is 6.9.0

**Comment by paul-shuvo** [comment]
Unfortunately, the library is tested on node version 12 onward. I assume there might be quite a few incompatibilities in terms of syntax. This library is fairly simple and small; I'd suggest, if you have time, to convert the code (syntax-wise) to the desired nodejs version.

**Comment by ptatap29** [comment]
thanks for replying.
