### ISSUE TITLE
Module not found: Can't resolve 'dns' When trying to import module into a TS project

### ISSUE THREAD

**Issue by m3c-ode** [paul-shuvo/nodejs-currency-converter#39]
When I try to import the module into my project (runs on next.js), as 

```
`// const CC = require('currency-converter-lt');
import * as CC from 'currency-converter-lt';`
```

I can't use it at all. Right away, I get : 

```
`error - ./node_modules/cacheable-lookup/source/index.js:10:2
Module not found: Can't resolve 'dns'

Import trace for requested module:
./node_modules/currency-converter-lt/node_modules/got/dist/source/core/index.js
./node_modules/currency-converter-lt/node_modules/got/dist/source/create.js
./node_modules/currency-converter-lt/node_modules/got/dist/source/index.js
./node_modules/currency-converter-lt/index.js
./src/...

https://nextjs.org/docs/messages/module-not-found`
```

**Comment by paul-shuvo** [comment]
Could you try 1) different internet network, or 2) TS-only project, and let me know if it still throws the error?

**Comment by m3c-ode** [comment]
Hi, so I tried on my backend project server (NestJS framework, with TS) and I get it to work. Not on my front-end then, using React/NextJS.

**Comment by paul-shuvo** [comment]
Yes, you can't use this package on front-end because of the __`got`__ package. I understand this issue to be resolved!
