### ISSUE TITLE
Any conversions leads to 0

### ISSUE THREAD

**Issue by Berkmann18** [paul-shuvo/nodejs-currency-converter#4]
I'm using the chained example to dynamically convert USD/EUR to GBP and recently the majority of values that gets passed to `amount()` leads to outputs of `0` when IIRC a month ago it was working.
I wonder if this package has reached its API limits or something.

**Comment by kirylAlexandrovich** [comment]
I found the problem, it is related to the parseFloat function in "rates" method.
When the float comes with a comma, the function returns 0

**Comment by anaskhalid98** [comment]
Me too, I'm facing the same issue
here's my code:

`const CC = require("currency-converter-lt");`
`let currencyConverter = new CC();`

`currencyConverter`
`  .from("USD")`
`.to("EUR")`
 `.amount(125)`
 `.convert()`
` .then((response) => `
`    console.log(response); //or do something else  });`

**Output : 0**

**Comment by paul-shuvo** [comment]
@Berkmann18 there is no API limit. 
@kirylAlexandrovich if the `parseFloat` gets a float value with a comma like this: `"ABC,def"`, it'll at least return `"ABC"`.
@anaskhalid98 I couldn't re-create the issue. I'm getting `106.25`.

As this library parses Google results, could you all share a screenshot of the result you get when you search `"usd to euro"` on google? I think it may return different results (string format) depending on your locale.

**Comment by kirylAlexandrovich** [comment]
@paul-shuvo thanks for solving the issue, this is the screenshot of google response
![Screenshot from 2021-07-19 18-50-56](https://user-images.githubusercontent.com/39993180/126190265-fed7f364-c123-448e-a26f-7d39069bbfb3.png)

**Comment by paul-shuvo** [comment]
The issue for having the __comma__ in the decimal value was fixed in release 1.1.4. (git commit ceaacf9).
I'm closing this issue. Feel free to reopen if the issue persists.
