### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by bond50** [paul-shuvo/nodejs-currency-converter#45]
I always get NaN  for example in the code below

currencyConverter.from("USD").to("GBP").amount(125).convert().then((response) => {
    console.log(response) //logs NaN
})

**Comment by paul-shuvo** [comment]
Which version of the package are you using?
Can you run your code on [runkit](https://runkit.com) and see if you can reproduce the error?

**Comment by paul-shuvo** [comment]
I'm closing this issue for lack of information provided.
