### ISSUE TITLE
Returning NAN

### ISSUE THREAD

**Issue by albus25** [paul-shuvo/nodejs-currency-converter#47]
I am using the latest beta version of this package, and it is returning NAN instead of converted value.
NodeVersion: 16.16.0
PackageVersion: 2.0.0-beta.0
OS: Windows 11

Code snippet
```
const CC = require("currency-converter-lt");
let currencyConverter = new CC({from:"USD", to:"INR", amount:1, isDecimalComma: true});
currencyConverter.convert().then((response) => {
    console.log(response) //or do something else
});
```

Output
![image](https://user-images.githubusercontent.com/37008711/221575249-42ed2d6e-c92a-43d1-a66e-b2e2c33a0116.png)

**Comment by paul-shuvo** [comment]
I've checked it on my machine and on replit; it seems to be working. Is it the only piece of code you're running? If not could you share more code?

**Comment by albus25** [comment]
Yes, this is the only code I am working on right now

**Comment by paul-shuvo** [comment]
Could you use version `1.3.1` and let me know if that fixes the issue.

**Comment by albus25** [comment]
I already tested it, it won't work for me

**Comment by paul-shuvo** [comment]
Could you use this [branch](https://github.com/paul-shuvo/nodejs-currency-converter/tree/47-returning-nan) and see if it works.

**Comment by albus25** [comment]
Yes, it is working now, thanks.
