### ISSUE TITLE
Update comorian currency from.  CA to KMF

### ISSUE THREAD

**Issue by Fanom2813** [paul-shuvo/nodejs-currency-converter#53]
hello, i have been using the library it just perfect thanks , but i noticed that comorian. currency. is not `CF` but `KMF`

**Comment by paul-shuvo** [comment]
Updated in the latest release ([4ffb9ac](https://github.com/paul-shuvo/nodejs-currency-converter/commit/4ffb9ac32d19299c1d599c72c661e83bfef8a59a)).
