### ISSUE TITLE
Incorrect conversions on bigger amounts

### ISSUE THREAD

**Issue by nakhtar313** [paul-shuvo/nodejs-currency-converter#56]
I'm converting USD to PKR. The conversion rate returned by the package is 0.0036 on Oct 17, 2023. Google also shows the same conversion rate. Now here's the tricky part: on the front, Google is showing a decimal precision of 2 digits, but during conversion, it uses more than 2 digits, which is the actual value (0.00362115). 

Therefore, when I convert 148,000,000 PKR to USD, the package returns 532,800. However, when I convert the same amount through Google, it returns me 535,952.84 USD. The difference is 2-3k USD, which is huge and this difference grows as the original amount grows 

I've attached the images for reference.

<img width="345" alt="Screenshot 2023-10-17 at 4 46 49 PM" src="https://github.com/paul-shuvo/nodejs-currency-converter/assets/105813655/df3f0921-b113-4d40-9ea8-6e2012dfc1f1">
<img width="497" alt="Screenshot 2023-10-17 at 4 52 18 PM" src="https://github.com/paul-shuvo/nodejs-currency-converter/assets/105813655/c47ef7be-3a3d-4dc5-8370-2dbe3b519bcf">

**Comment by paul-shuvo** [comment]
I've pushed some changes to the latest version; it should be fixed now. If the problem persists, feel free to open this issue.
