### ISSUE TITLE
API seems not working in night

### ISSUE THREAD

**Issue by ankitshantiinfotech** [paul-shuvo/nodejs-currency-converter#57]
Hi,

I have implemented currency conversion API and after 6.00 PM (IST) API seems not working till morning. I always get The request timed out error

`api -http://78.46.210.25:8011/api/user/amount-conversion-
params -{
  amount = "44.78";
  "convert_from" = USD;
  "convert_to" = AUD;
  "user_id" = 32;
}-
error-Optional(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2103, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <C5717D2E-2601-4719-89F5-36AA7FFF3034>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
  "LocalDataTask <C5717D2E-2601-4719-89F5-36AA7FFF3034>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://78.46.210.25:8011/api/user/amount-conversion, NSErrorFailingURLKey=http://78.46.210.25:8011/api/user/amount-conversion, _kCFStreamErrorDomainKey=4})-`

Is there any time boundation with this api's

**Comment by ankitshantiinfotech** [comment]
@paul-shuvo

**Comment by paul-shuvo** [comment]
I checked it on runkit, where it seems to work fine. The problem might be too many requests were being sent.

**Comment by ankitshantiinfotech** [comment]
@paul-shuvo So what's the ideal limit of it ? I am planning to release in my app upcoming versions, and my client base is large so what we should do in that case ?

**Comment by paul-shuvo** [comment]
Are you using the lib on the client side or on the server side?

Edit: This lib scrapes Google search results, so if you're sending lots of repeated requests, google might blacklist the ip; the best is to implement it on the client side (desktop and perhaps mobile apps).

**Comment by ankitshantiinfotech** [comment]
Yes @paul-shuvo,

I have created a custom end point in which i am taking params from app side convert_from, convert_to and currency_to_convert. and calling your code in that API

`let currencyConverter = new CC({from:"USD", to:"JPY", amount:100, isDecimalComma:true})
`

**Comment by paul-shuvo** [comment]
@ankitshantiinfotech as I mentioned above, you've to have the code run on the client side as too many requests (if implemented on the server side) will surely blacklist the IP.

**Comment by ankitshantiinfotech** [comment]
@paul-shuvo What will be the alternatives for that now ?

**Comment by paul-shuvo** [comment]
You've to run it on the client side (Nodejs).
