### ISSUE TITLE
Requests take almost a full second

### ISSUE THREAD

**Issue by Kimi99** [paul-shuvo/nodejs-currency-converter#58]
Hello.

I've been looking into this library and I've managed to implement it into my project, but I am curious if the requests should take that much time to convert values.

My scenario: I have a list of values, ~20 numbers and I'm iterating through them and using the convert method on every single one.
After that I just return the values inside of a response object that I created.
The only problem is that, the API takes 13s to complete all the conversions which means it's close to a second for every conversion.

Is this an actual behavior or maybe I have made a mistake in the implementation of the library?
@paul-shuvo

**Comment by paul-shuvo** [comment]
It is scraping/parsing out the conversion rates from search results, so I'm assuming it would be slower and also, might be dependent on the internet speed as well.

**Comment by Kimi99** [comment]
Can you elaborate more on the scraping implementation, I tried looking into the code but wasn't really successful.

**Comment by paul-shuvo** [comment]
The scraping happens between line 273 to 302:

```javascript

      return new Promise((resolve, reject) => {
          request(`https://www.google.com/search?q=${this.currencyAmount}+${this.currencyFrom}+to+${this.currencyTo}+&hl=en`, function(error, response, body) {
            if (error) {
              return reject(error);
            } else {
              resolve(body);
            }
          });
        }).then((body) => {
          return cheerio.load(body)
        })
        .then(($) => {
          return $(".iBp4i").text().split(" ")[0]
        })
        .then((rates) => {
          if (this.isDecimalComma) {
            if (rates.includes("."))
              rates = this.replaceAll(rates, ".", "")
            if (rates.includes(","))
              rates = this.replaceAll(rates, ",", ".")
          } else {
            if (rates.includes(","))
              rates = this.replaceAll(rates, ",", "")
          }
          rates = parseFloat(rates) / this.currencyAmount
          if (this.isRatesCaching) {
            this.addRateToRatesCache(currencyPair, rates);
          }
          return rates
        })
```

**Comment by Kimi99** [comment]
Thanks!
Closing this since all questions are answered.
