### ISSUE TITLE
How to run it from browser. Seeing error The package "x" wasn't found 

### ISSUE THREAD

**Issue by ishandutta2007** [paul-shuvo/nodejs-currency-converter#60]
installed `
    "currency-converter-lt": "^2.0.1",
`
then 
```
import CC from "currency-converter-lt";
let currencyConverter = new CC({from:"USD", to:"INR", amount:1, isDecimalComma:true})

currencyConverter.convert().then((response) => {
    console.log("rate", response);
})
```

Error:
```
The package "url" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

not just for url package I am seeing the same error for a buynch of other packages like `crypto, https, stream,util`

**Comment by paul-shuvo** [comment]
This might be an issue out of the scope of this project. In any case, could you try running it on runkit and let me know if it shows any error?

**Comment by ishandutta2007** [comment]
> This might be an issue out of the scope of this project. 

@paul-shuvo well then do you know of any client side library ? I stumbled here trying to find a library to integrate in my react project.
