### ISSUE TITLE
All responses return NaN

### ISSUE THREAD

**Issue by annasmykova** [paul-shuvo/nodejs-currency-converter#61]
For version `"currency-converter-lt": "^2.0.0"`
```
new CC({ from: 'UAH', to: 'USD', amount: 3800 }).convert().then(test => {
	console.log(test); // Returns NaN
})
new CC({ from: 'UAH', to: 'USD', amount: 3800 }).rates().then(rates => {
	console.log(rates); // Returns NaN
})
```
No difference on what `from` or `to` are used, all responses return NaNs.

**Comment by laam-egg** [comment]
I've been suffering from the same problem, please fix this asap

**Comment by paul-shuvo** [comment]
Could you reproduce it on runkit and send the link?
