### ISSUE TITLE
EUR returned Nan

### ISSUE THREAD

**Issue by Tini79** [paul-shuvo/nodejs-currency-converter#64]
When I try to convert from IDR to EUR it returned Nan, but others are fine. How could it be like this?

**Comment by Tini79** [comment]
I tried to run my code on runkit and still!

**Comment by paul-shuvo** [comment]
Google doesn't convert IDR to EUR, but does EUR to IDR. So, get the conversion from EUR to IDR,; let's assume that conversion rate is `EURToIDR` and then IDR to EUR should be `1/EURToIDR`. I'll add this as a fix for the next release.

**Comment by Tini79** [comment]
I see, thank you for your response. I'll try your solution then to solve this issue.

**Comment by Tini79** [comment]
Hi Paul,

I still have a question. So, in case, I have the same problem with another
currency, should I use this method to convert them?

Regards,
Tini

Pada Sel, 18 Jun 2024 pukul 23.31 paul ***@***.***> menulis:

**Comment by paul-shuvo** [comment]
For the time being, yes. I'll add this automated check in the next release.

**Comment by Tini79** [comment]
Alright then. Thank you very much Paul.
