### ISSUE TITLE
process is not defined currency-convert-It.js

### ISSUE THREAD

**Issue by ullaskunder1** [paul-shuvo/nodejs-currency-converter#66]
I am using Vite typesciprt and got into this issue:

![image](https://github.com/paul-shuvo/nodejs-currency-converter/assets/163815920/6034029f-7dca-4738-9fc8-23f6ba4c34c7)

```
import CurrencyConverter from 'currency-converter-lt';

const currencyConverter = new CurrencyConverter({
  isRatesCaching: true,
  ratesCacheDuration: 3600
});

export const convertToYen = async (amount: number): Promise<number> => {
  console.log('amount', amount)
  const convertedAmount = await currencyConverter.from('USD').to('JPY').amount(amount).convert();
  return convertedAmount;
};
```

**Comment by paul-shuvo** [comment]
I'm assuming this is a Vite issue. Have you checked the suggested link provided in the error message? Also, take a look into [this](https://github.com/vitejs/vite/discussions/4479). I'm closing this issue. If you still seem to have the issue or have some more information, feel free to open the issue again.

**Comment by ullaskunder1** [comment]
still got no help
